[project]
name = "test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "openai-agents>=0.0.9",
    "openai>=1.72.0",
    "pydantic>=2.11.3",
    "exa-py>=1.11.0",
    "python-dotenv>=1.1.0",
]
